default:

  project_name                                        : "{project_name}"
  schema_name                                         : "{schema_name}"
  dsn_staging                                         : "cdw_cache_staging"
  # dsn_centricity                                      : "cdw_outpost"
  # dsn_omop                                            : "cdw_omop_1"
  # dsn_gecb                                            : "cdw_waystation_idx"
  # dsn_security                                        : "BbmcSecurity"

  directory_file_server                               : "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}"
  directory_output                                    : "{directory_file_server}/data/derived/%Y-%m-%d"
  # path_output_summary                                 : "{directory_file_server}/data/derived/%Y-%m-%d/_summary.csv"
  # path_output_description                             : "{directory_file_server}/data/derived/%Y-%m-%d/_description.md"
  # directory_meditech_triage                           : "//pedsis/peds/data/BBMC/ou-medicine"

  # path_log_flow                                       : !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")
  # path_log_flow                                       : !expr strftime(Sys.time(), "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")

  # path_metadata_ss_dx                                 : "data-public/metadata/ss-dx.csv"
  
  # time_zone_local               :  "America/Chicago"          # Force time calculations to be local, in case remotely run.
  
  # ---- Validation Ranges & Patterns ----
  # range_record_id               : !expr c(1L, 999999L)
  # range_dob                     : !expr c(as.Date("2010-01-01"), Sys.Date() + lubridate::days(1))
  # range_date_entry              : !expr c(as.Date("2019-01-01"), Sys.Date())
  # range_datetime_entry          : !expr c(as.POSIXct("2019-01-01", tz="America/Chicago"), Sys.time())
  # range_hdid                    : !expr c(-1L, 999999908L)
  # max_age                       : 25
  # pattern_mrn_centricity        : "^\\d{16}$"                 # The 64-bit int is more easily validated as a character.
  # pattern_mrn_flowcast          : "^(?:\\d{6,8}|E\\d{9})$"    # There are 22 values with junky meditech mrns.
  # pattern_mrn_meditech          : "^E\\d{9}$"
  # pattern_account_meditech      : "^E\\d{11}$"
  # pattern_account_icd           : "^[A-TV-Z][0-9][0-9AB]\.?[0-9A-TV-Z]{0,4}|\d{3}\.?\d{0,2}|E\d{3}\.?\d?|V\d{2}\.?\d{0,2}$" # From https://www.johndcook.com/blog/2019/05/05/regex_icd_codes/
  # pattern_account_icd10         : "^[A-TV-Z][0-9][0-9AB]\.?[0-9A-TV-Z]{0,4}$"
  # pattern_account_icd09         : "^\d{3}\.?\d{0,2}|E\d{3}\.?\d?|V\d{2}\.?\d{0,2}$"
  
  # tables_to_scribe:
  #   -
  #     name: person
  #     sql: "SELECT * FROM {schema_name}.person"
  #     columns_include: ""
  #     #columns_exclude: ""
  #     path_output: "{directory_output}/person.csv"
  #     #path_output: "data-public/derived/%Y-%m-%d/person.csv"
  #     row_unit: each row represents a distinct patient.
  #   -
  #     name: obs
  #     sql: ""
  #     columns_include: "mrn_flowcast, obs_date, obs_term, obs_value"
  #     path_output: "{directory_output}/obs.csv"
  #     #path_output: "data-public/derived/%Y-%m-%d/obs.csv"
  #     row_unit: each row represents a distinct measurement
  #   -
  #     name: medicate
  #     columns_include: "*"
  #     #columns_exclude: "start_date, stop_date"
  #     path_output: "{directory_output}/medicate.csv"
  #     #path_output: "data-public/derived/%Y-%m-%d/medicate.csv"
  #     row_unit: each row represents a distinct prescription

  # sweep and specify
  # fs_input_review_required_centricity_diagnosis       : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-required/diagnosis"
  # fs_input_review_required_centricity_location        : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-required/location"
  # fs_input_review_required_centricity_medication      : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-required/medication"
  # fs_input_review_required_centricity_obs             : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-required/obs"
  # fs_input_review_required_idx_cpt                    : "{directory_output}/data-public/sweep-and-specify-idx/input/review-required/cpt"
  # fs_input_review_required_idx_diagnosis              : "{directory_output}/data-public/sweep-and-specify-idx/input/review-required/diagnosis"
  # fs_input_review_required_idx_location               : "{directory_output}/data-public/sweep-and-specify-idx/input/review-required/location"
  # fs_input_review_required_idx_sched_location         : "{directory_output}/data-public/sweep-and-specify-idx/input/review-required/sched-location"
  # fs_input_review_skip_centricity_diagnosis           : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-skip/diagnosis"
  # fs_input_review_skip_centricity_location            : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-skip/location"
  # fs_input_review_skip_centricity_medication          : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-skip/medication"
  # fs_input_review_skip_centricity_obs                 : "{directory_output}/data-public/sweep-and-specify-centricity/input/review-skip/obs"
  # fs_input_review_skip_idx_cpt                        : "{directory_output}/data-public/sweep-and-specify-idx/input/review-skip/cpt"
  # fs_input_review_skip_idx_diagnosis                  : "{directory_output}/data-public/sweep-and-specify-idx/input/review-skip/diagnosis"
  # fs_input_review_skip_idx_location                   : "{directory_output}/data-public/sweep-and-specify-idx/input/review-skip/location"
  # fs_input_review_skip_idx_sched_location             : "{directory_output}/data-public/sweep-and-specify-idx/input/review-skip/sched-location"
  # fs_review_centricity_diagnosis                      : "{directory_output}/data-public/sweep-and-specify-centricity/review/diagnosis"
  # fs_review_centricity_location                       : "{directory_output}/data-public/sweep-and-specify-centricity/review/location"
  # fs_review_centricity_medication                     : "{directory_output}/data-public/sweep-and-specify-centricity/review/medication"
  # fs_review_centricity_obs                            : "{directory_output}/data-public/sweep-and-specify-centricity/review/obs"
  # fs_review_idx_cpt                                   : "{directory_output}/data-public/sweep-and-specify-idx/review/cpt"
  # fs_review_idx_diagnosis                             : "{directory_output}/data-public/sweep-and-specify-idx/review/diagnosis"
  # fs_review_idx_location                              : "{directory_output}/data-public/sweep-and-specify-idx/review/location"
  # fs_review_idx_sched_location                        : "{directory_output}/data-public/sweep-and-specify-idx/review/sched-location"
  # fs_review_original_centricity_diagnosis             : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-original/diagnosis"
  # fs_review_original_centricity_location              : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-original/location"
  # fs_review_original_centricity_medication            : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-original/medication"
  # fs_review_original_centricity_obs                   : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-original/obs"
  # fs_review_original_idx_cpt                          : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-original/cpt"
  # fs_review_original_idx_diagnosis                    : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-original/diagnosis"
  # fs_review_original_idx_location                     : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-original/location"
  # fs_review_original_idx_sched_location               : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-original/sched-location"
  # fs_to_database_centricity_diagnosis                 : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-to-database/diagnosis"
  # fs_to_database_centricity_location                  : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-to-database/location"
  # fs_to_database_centricity_medication                : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-to-database/medication"
  # fs_to_database_centricity_obs                       : "{directory_output}/data-public/sweep-and-specify-centricity/reviewed-to-database/obs"
  # fs_to_database_idx_cpt                              : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-to-database/cpt"
  # fs_to_database_idx_diagnosis                        : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-to-database/diagnosis"
  # fs_to_database_idx_location                         : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-to-database/location"
  # fs_to_database_idx_sched_location                   : "{directory_output}/data-public/sweep-and-specify-idx/reviewed-to-database/sched-location"

  # fs_archive_centricity                               : "{directory_output}/data-public/sweep-and-specify-centricity/archive"
  # fs_archive_idx                                      : "{directory_output}/data-public/sweep-and-specify-idx/archive"

  # gt_sql_review_required_centricity_diagnosis         : "manipulation/sweep-and-specify/sql/review-required-centricity-diagnosis.sql"
  # gt_sql_review_required_centricity_location          : "manipulation/sweep-and-specify/sql/review-required-centricity-location.sql"
  # gt_sql_review_required_centricity_medication        : "manipulation/sweep-and-specify/sql/review-required-centricity-medication.sql"
  # gt_sql_review_required_centricity_obs               : "manipulation/sweep-and-specify/sql/review-required-centricity-obs.sql"
  # gt_sql_review_required_idx_cpt                      : "manipulation/sweep-and-specify/sql/review-required-idx-cpt.sql"
  # gt_sql_review_required_idx_diagnosis                : "manipulation/sweep-and-specify/sql/review-required-idx-diagnosis.sql"
  # gt_sql_review_required_idx_location                 : "manipulation/sweep-and-specify/sql/review-required-idx-location.sql"
  # gt_sql_review_required_idx_sched_location           : "manipulation/sweep-and-specify/sql/review-required-idx-sched-location.sql"
  # gt_sql_review_skip_centricity_diagnosis             : "manipulation/sweep-and-specify/sql/review-skip-centricity-diagnosis.sql"
  # gt_sql_review_skip_centricity_location              : "manipulation/sweep-and-specify/sql/review-skip-centricity-location.sql"
  # gt_sql_review_skip_centricity_medication            : "manipulation/sweep-and-specify/sql/review-skip-centricity-medication.sql"
  # gt_sql_review_skip_centricity_obs                   : "manipulation/sweep-and-specify/sql/review-skip-centricity-obs.sql"
  # gt_sql_review_skip_idx_cpt                          : "manipulation/sweep-and-specify/sql/review-skip-idx-cpt.sql"
  # gt_sql_review_skip_idx_diagnosis                    : "manipulation/sweep-and-specify/sql/review-skip-idx-diagnosis.sql"
  # gt_sql_review_skip_idx_location                     : "manipulation/sweep-and-specify/sql/review-skip-idx-location.sql"
  # gt_sql_review_skip_idx_sched_location               : "manipulation/sweep-and-specify/sql/review-skip-idx-sched-location.sql"

  # #csv report generator
  # gt_sql_queries_to_csv                               : "manipulation/sql-queries-to-csv-report/sql-to-generate-csv"
  # gt_sql_csv_report_generated                         : "manipulation/sql-queries-to-csv-report/sql-csv-report-generated"
  # fs_csv_report                                       : "{directory_output}/csv-report"

  # path_database                                       : "data-public/raw/emr-mock.sqlite"
  # project_name                                        : !expr basename(getwd())
