default:

  dsn_staging                                         :   "cdw_cache_staging"
  # dsn_centricity                                      :   "cdw_outpost"
  # dsn_idx                                             :   "cdw_waystation_idx"
  schema_name                                         :   "{project_name}"

  tables_to_scribe:
    -
      name: person
      sql: "SELECT * FROM {project_name}.person"
      columns_include: ""
      #columns_exclude: ""
      path_output: "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data/derived/person.csv"
    -
      name: obs
      sql: ""
      columns_include: "mrn_flowcast, obs_date, obs_term, obs_value"
      path_output: "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data/derived/obs.csv"
    -
      name: medicate
      columns_include: "*"
      #columns_exclude: "start_date, stop_date"
      path_output: "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data/derived/medicate.csv"

 # #sweep and specify
 # fs_input_review_required_centricity_diagnosis       :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-required/diagnosis"
 # fs_input_review_required_centricity_location        :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-required/location"
 # fs_input_review_required_centricity_medication      :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-required/medication"
 # fs_input_review_required_centricity_obs             :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-required/obs"
 # fs_input_review_required_idx_cpt                    :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-required/cpt"
 # fs_input_review_required_idx_diagnosis              :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-required/diagnosis"
 # fs_input_review_required_idx_location               :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-required/location"
 # fs_input_review_required_idx_sched_location         :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-required/sched-location"
 # fs_input_review_skip_centricity_diagnosis           :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-skip/diagnosis"
 # fs_input_review_skip_centricity_location            :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-skip/location"
 # fs_input_review_skip_centricity_medication          :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-skip/medication"
 # fs_input_review_skip_centricity_obs                 :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/input/review-skip/obs"
 # fs_input_review_skip_idx_cpt                        :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-skip/cpt"
 # fs_input_review_skip_idx_diagnosis                  :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-skip/diagnosis"
 # fs_input_review_skip_idx_location                   :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-skip/location"
 # fs_input_review_skip_idx_sched_location             :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/input/review-skip/sched-location"
 # fs_review_centricity_diagnosis                      :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/review/diagnosis"
 # fs_review_centricity_location                       :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/review/location"
 # fs_review_centricity_medication                     :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/review/medication"
 # fs_review_centricity_obs                            :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/review/obs"
 # fs_review_idx_cpt                                   :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/review/cpt"
 # fs_review_idx_diagnosis                             :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/review/diagnosis"
 # fs_review_idx_location                              :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/review/location"
 # fs_review_idx_sched_location                        :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/review/sched-location"
 # fs_review_original_centricity_diagnosis             :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-original/diagnosis"
 # fs_review_original_centricity_location              :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-original/location"
 # fs_review_original_centricity_medication            :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-original/medication"
 # fs_review_original_centricity_obs                   :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-original/obs"
 # fs_review_original_idx_cpt                          :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-original/cpt"
 # fs_review_original_idx_diagnosis                    :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-original/diagnosis"
 # fs_review_original_idx_location                     :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-original/location"
 # fs_review_original_idx_sched_location               :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-original/sched-location"
 # fs_to_database_centricity_diagnosis                 :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-to-database/diagnosis"
 # fs_to_database_centricity_location                  :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-to-database/location"
 # fs_to_database_centricity_medication                :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-to-database/medication"
 # fs_to_database_centricity_obs                       :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/reviewed-to-database/obs"
 # fs_to_database_idx_cpt                              :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-to-database/cpt"
 # fs_to_database_idx_diagnosis                        :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-to-database/diagnosis"
 # fs_to_database_idx_location                         :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-to-database/location"
 # fs_to_database_idx_sched_location                   :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/reviewed-to-database/sched-location"

 # gt_sql_review_required_centricity_diagnosis         : "manipulation/sweep-and-specify/sql/review-required-centricity-diagnosis.sql"
 # gt_sql_review_required_centricity_location          : "manipulation/sweep-and-specify/sql/review-required-centricity-location.sql"
 # gt_sql_review_required_centricity_medication        : "manipulation/sweep-and-specify/sql/review-required-centricity-medication.sql"
 # gt_sql_review_required_centricity_obs               : "manipulation/sweep-and-specify/sql/review-required-centricity-obs.sql"
 # gt_sql_review_required_idx_cpt                      : "manipulation/sweep-and-specify/sql/review-required-idx-cpt.sql"
 # gt_sql_review_required_idx_diagnosis                : "manipulation/sweep-and-specify/sql/review-required-idx-diagnosis.sql"
 # gt_sql_review_required_idx_location                 : "manipulation/sweep-and-specify/sql/review-required-idx-location.sql"
 # gt_sql_review_required_idx_sched_location           : "manipulation/sweep-and-specify/sql/review-required-idx-sched-location.sql"
 # gt_sql_review_skip_centricity_diagnosis             : "manipulation/sweep-and-specify/sql/review-skip-centricity-diagnosis.sql"
 # gt_sql_review_skip_centricity_location              : "manipulation/sweep-and-specify/sql/review-skip-centricity-location.sql"
 # gt_sql_review_skip_centricity_medication            : "manipulation/sweep-and-specify/sql/review-skip-centricity-medication.sql"
 # gt_sql_review_skip_centricity_obs                   : "manipulation/sweep-and-specify/sql/review-skip-centricity-obs.sql"
 # gt_sql_review_skip_idx_cpt                          : "manipulation/sweep-and-specify/sql/review-skip-idx-cpt.sql"
 # gt_sql_review_skip_idx_diagnosis                    : "manipulation/sweep-and-specify/sql/review-skip-idx-diagnosis.sql"
 # gt_sql_review_skip_idx_location                     : "manipulation/sweep-and-specify/sql/review-skip-idx-location.sql"
 # gt_sql_review_skip_idx_sched_location               : "manipulation/sweep-and-specify/sql/review-skip-idx-sched-location.sql"

 # fs_archive_centricity                               : "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-centricity/archive"
 # fs_archive_idx                                      : "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/data-public/sweep-and-specify-idx/archive"

 # #csv report generator
 # gt_sql_queries_to_csv                               :   "manipulation/sql-queries-to-csv-report/sql-to-generate-csv"
 # gt_sql_csv_report_generated                         :   "manipulation/sql-queries-to-csv-report/sql-csv-report-generated"
 # fs_csv_report                                       :   "//pedsis/peds/data/BBMC/prairie-outpost/{project_name}/csv-report"

  path_database                                        : "data-public/raw/emr-mock.sqlite"
